name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - 'tools/**'
      - '**/*.md'
      - '**/*.yml'
      - '*.code-workspace'
      - '.gitignore'

  pull_request:
    branches: [main]
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - 'tools/**'
      - '**/*.md'
      - '**/*.yml'
      - '*.code-workspace'
      - '.gitignore'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    # only build and push if this is not a pull request
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit
